/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "@aws-amplify/ui-react/internal";
import { Icon, Text, View } from "@aws-amplify/ui-react";
export default function Calendar1(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="251px"
      height="238px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "Calendar1")}
      {...rest}
    >
      <View
        width="251px"
        height="238px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="0%"
        left="0%"
        right="0%"
        boxShadow="0px 1px 4px rgba(0, 0, 0, 0.25)"
        borderRadius="4px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(255,255,255,1)"
        {...getOverrideProps(overrides, "Rectangle 147")}
      ></View>
      <View
        width="238px"
        height="186px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        overflow="hidden"
        position="absolute"
        top="18.49%"
        bottom="3.36%"
        left="2.39%"
        right="2.79%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Frame 436")}
      >
        <View
          width="220px"
          height="27px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          overflow="hidden"
          position="absolute"
          top="2.15%"
          bottom="83.33%"
          left="4.2%"
          right="3.36%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Frame 437")}
        >
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="20px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="22.22%"
            bottom="25.93%"
            left="3.64%"
            right="87.27%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Mo"
            {...getOverrideProps(overrides, "Mo")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="13px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="22.22%"
            bottom="25.93%"
            left="62.73%"
            right="31.36%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Fr"
            {...getOverrideProps(overrides, "Fr")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="21px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="22.22%"
            bottom="25.93%"
            left="31.82%"
            right="58.64%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="We"
            {...getOverrideProps(overrides, "We")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="16px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="22.22%"
            bottom="25.93%"
            left="91.36%"
            right="1.36%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Su"
            {...getOverrideProps(overrides, "Su")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="15px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="22.22%"
            bottom="25.93%"
            left="18.18%"
            right="75%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Tu"
            {...getOverrideProps(overrides, "Tu")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="16px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="22.22%"
            bottom="25.93%"
            left="76.82%"
            right="15.91%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Sa"
            {...getOverrideProps(overrides, "Sa")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="15px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="22.22%"
            bottom="25.93%"
            left="48.64%"
            right="44.55%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="Th"
            {...getOverrideProps(overrides, "Th")}
          ></Text>
        </View>
        <View
          width="227px"
          height="151px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          overflow="hidden"
          position="absolute"
          top="18.82%"
          bottom="0%"
          left="3.36%"
          right="1.26%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Frame 438")}
        >
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="14px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="45.7%"
            bottom="45.03%"
            left="61.67%"
            right="32.16%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="16"
            {...getOverrideProps(overrides, "16")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="13px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="23.84%"
            bottom="66.89%"
            left="61.67%"
            right="32.6%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="11"
            {...getOverrideProps(overrides, "11")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="17px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="66.89%"
            bottom="23.84%"
            left="61.67%"
            right="30.84%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="23"
            {...getOverrideProps(overrides, "23")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="17px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="86.09%"
            bottom="4.64%"
            left="61.67%"
            right="30.84%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="30"
            {...getOverrideProps(overrides, "3037823944")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="15px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="66.89%"
            bottom="23.84%"
            left="18.5%"
            right="74.89%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="20"
            {...getOverrideProps(overrides, "20")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="15px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="45.7%"
            bottom="45.03%"
            left="18.5%"
            right="74.89%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="13"
            {...getOverrideProps(overrides, "1337823946")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="13px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="23.84%"
            bottom="66.89%"
            left="18.5%"
            right="75.77%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children=" 8"
            {...getOverrideProps(overrides, "8")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="0px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="2.65%"
            bottom="88.08%"
            left="18.5%"
            right="81.5%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="  "
            {...getOverrideProps(overrides, "Text")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="15px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="86.09%"
            bottom="4.64%"
            left="18.5%"
            right="74.89%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="27"
            {...getOverrideProps(overrides, "27")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="15px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="66.89%"
            bottom="23.84%"
            left="4.41%"
            right="88.99%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="19"
            {...getOverrideProps(overrides, "19")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="15px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="45.7%"
            bottom="45.03%"
            left="4.41%"
            right="88.99%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="12"
            {...getOverrideProps(overrides, "1237823951")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="12px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="23.84%"
            bottom="66.89%"
            left="4.41%"
            right="90.31%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children=" 7"
            {...getOverrideProps(overrides, "7")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(177,177,178,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="16px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="2.65%"
            bottom="88.08%"
            left="4.41%"
            right="88.55%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="30"
            {...getOverrideProps(overrides, "3037823953")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="16px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="86.09%"
            bottom="4.64%"
            left="4.41%"
            right="88.55%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="26"
            {...getOverrideProps(overrides, "26")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="15px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="45.7%"
            bottom="45.03%"
            left="75.77%"
            right="17.62%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="17"
            {...getOverrideProps(overrides, "17")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="15px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="23.84%"
            bottom="66.89%"
            left="75.77%"
            right="17.62%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="12"
            {...getOverrideProps(overrides, "1237823956")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="14px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="2.65%"
            bottom="88.08%"
            left="75.77%"
            right="18.06%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children=" 5"
            {...getOverrideProps(overrides, "5")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="17px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="66.89%"
            bottom="23.84%"
            left="75.77%"
            right="16.74%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="24"
            {...getOverrideProps(overrides, "24")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="15px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="86.09%"
            bottom="4.64%"
            left="75.77%"
            right="17.62%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="31"
            {...getOverrideProps(overrides, "31")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="14px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="66.89%"
            bottom="23.84%"
            left="33.04%"
            right="60.79%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="21"
            {...getOverrideProps(overrides, "21")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="14px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="45.7%"
            bottom="45.03%"
            left="33.04%"
            right="60.79%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="14"
            {...getOverrideProps(overrides, "14")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(124,124,124,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="16px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="2.65%"
            bottom="88.08%"
            left="33.04%"
            right="59.91%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="  2"
            {...getOverrideProps(overrides, "2")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(124,124,124,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="15px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="2.65%"
            bottom="88.08%"
            left="18.5%"
            right="74.89%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="  1"
            {...getOverrideProps(overrides, "137823964")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(124,124,124,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="17px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="2.65%"
            bottom="88.08%"
            left="59.91%"
            right="32.6%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="  4"
            {...getOverrideProps(overrides, "4")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="16px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="86.09%"
            bottom="4.64%"
            left="33.04%"
            right="59.91%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="28"
            {...getOverrideProps(overrides, "28")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="15px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="45.7%"
            bottom="45.03%"
            left="89.87%"
            right="3.52%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="18"
            {...getOverrideProps(overrides, "18")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="15px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="23.84%"
            bottom="66.89%"
            left="89.87%"
            right="3.52%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="13"
            {...getOverrideProps(overrides, "1337823968")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="13px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="2.65%"
            bottom="88.08%"
            left="90.75%"
            right="3.52%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children=" 6"
            {...getOverrideProps(overrides, "6")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="16px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="66.89%"
            bottom="23.84%"
            left="89.43%"
            right="3.52%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="25"
            {...getOverrideProps(overrides, "25")}
          ></Text>
          <Text
            fontFamily="Inter"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="13.3125px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="12px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="86.09%"
            bottom="4.64%"
            left="91.19%"
            right="3.52%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children=" 1"
            {...getOverrideProps(overrides, "137823971")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="15px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="66.89%"
            bottom="23.84%"
            left="48.02%"
            right="45.37%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="22"
            {...getOverrideProps(overrides, "22")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="14px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="45.7%"
            bottom="45.03%"
            left="48.02%"
            right="45.81%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="15"
            {...getOverrideProps(overrides, "15")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="14px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="23.84%"
            bottom="66.89%"
            left="48.02%"
            right="45.81%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="10"
            {...getOverrideProps(overrides, "10")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(124,124,124,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="11px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="2.65%"
            bottom="88.08%"
            left="48.02%"
            right="47.14%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children=" 3"
            {...getOverrideProps(overrides, "3")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="11px"
            fontWeight="400"
            color="rgba(37,37,37,1)"
            lineHeight="16.5px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="15px"
            height="14px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="86.09%"
            bottom="4.64%"
            left="48.02%"
            right="45.37%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="29"
            {...getOverrideProps(overrides, "29")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="10px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="15px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="10px"
            height="10px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="36.42%"
            bottom="56.95%"
            left="18.94%"
            right="76.65%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="✅"
            {...getOverrideProps(overrides, "\u270537943149")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="10px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="15px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="10px"
            height="10px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="36.42%"
            bottom="56.95%"
            left="4.85%"
            right="90.75%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="✅"
            {...getOverrideProps(overrides, "\u270537943600")}
          ></Text>
          <Text
            fontFamily="Poppins"
            fontSize="10px"
            fontWeight="400"
            color="rgba(0,0,0,1)"
            lineHeight="15px"
            textAlign="left"
            display="block"
            direction="column"
            justifyContent="unset"
            width="10px"
            height="10px"
            gap="unset"
            alignItems="unset"
            position="absolute"
            top="14.57%"
            bottom="78.81%"
            left="91.63%"
            right="3.96%"
            padding="0px 0px 0px 0px"
            whiteSpace="pre-wrap"
            children="✅"
            {...getOverrideProps(overrides, "\u270537943640")}
          ></Text>
          <View
            width="33px"
            height="31px"
            display="block"
            gap="unset"
            alignItems="unset"
            justifyContent="unset"
            overflow="hidden"
            position="absolute"
            top="19.21%"
            bottom="60.26%"
            left="29.52%"
            right="55.95%"
            padding="0px 0px 0px 0px"
            {...getOverrideProps(overrides, "Frame 440")}
          >
            <View
              width="23.72px"
              height="20px"
              display="block"
              gap="unset"
              alignItems="unset"
              justifyContent="unset"
              position="absolute"
              top="16.13%"
              bottom="19.35%"
              left="9.38%"
              right="18.75%"
              borderRadius="2px"
              padding="0px 0px 0px 0px"
              backgroundColor="rgba(4,125,149,1)"
              {...getOverrideProps(overrides, "Rectangle 150")}
            ></View>
            <Text
              fontFamily="Poppins"
              fontSize="11px"
              fontWeight="400"
              color="rgba(255,255,255,1)"
              lineHeight="16.5px"
              textAlign="left"
              display="block"
              direction="column"
              justifyContent="unset"
              width="13.41px"
              height="14px"
              gap="unset"
              alignItems="unset"
              position="absolute"
              top="22.58%"
              bottom="32.26%"
              left="25%"
              right="34.38%"
              padding="0px 0px 0px 0px"
              whiteSpace="pre-wrap"
              children=" 9"
              {...getOverrideProps(overrides, "9")}
            ></Text>
          </View>
        </View>
      </View>
      <View
        width="224px"
        height="31px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        overflow="hidden"
        position="absolute"
        top="5.46%"
        bottom="81.51%"
        left="4.78%"
        right="5.98%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Frame 439")}
      >
        <Text
          fontFamily="Poppins"
          fontSize="12px"
          fontWeight="400"
          color="rgba(37,37,37,1)"
          lineHeight="18px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="37.84px"
          height="12.11px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="24%"
          bottom="36.93%"
          left="63.43%"
          right="19.67%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="2022"
          {...getOverrideProps(overrides, "2022")}
        ></Text>
        <Icon
          width="10.6px"
          height="7.57px"
          viewBox={{
            minX: 0,
            minY: 0,
            width: 10.596435546875,
            height: 7.56884765625,
          }}
          paths={[
            {
              d: "M5.29819 0L9.88656 5.67663L0.709823 5.67663L5.29819 0Z",
              fill: "rgba(4,125,149,1)",
              fillRule: "nonzero",
            },
          ]}
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="63.89%"
          bottom="11.69%"
          left="83.48%"
          right="11.79%"
          transformOrigin="top left"
          transform="rotate(-180deg)"
          {...getOverrideProps(overrides, "Polygon 19")}
        ></Icon>
        <Icon
          width="10.6px"
          height="7.57px"
          viewBox={{
            minX: 0,
            minY: 0,
            width: 10.596435546875,
            height: 7.56884765625,
          }}
          paths={[
            {
              d: "M5.29819 0L9.88656 5.67663L0.709823 5.67663L5.29819 0Z",
              fill: "rgba(4,125,149,1)",
              fillRule: "nonzero",
            },
          ]}
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="38.65%"
          bottom="36.93%"
          left="53.74%"
          right="41.53%"
          transformOrigin="top left"
          transform="rotate(0deg)"
          {...getOverrideProps(overrides, "Polygon 20")}
        ></Icon>
        <Text
          fontFamily="Poppins"
          fontSize="12px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="18px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="72px"
          height="17px"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="22.58%"
          bottom="22.58%"
          left="22.32%"
          right="45.54%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="December "
          {...getOverrideProps(overrides, "December")}
        ></Text>
      </View>
    </View>
  );
}
