/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "@aws-amplify/ui-react/internal";
import { Icon, Text, View } from "@aws-amplify/ui-react";
export default function Calendar3(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="251px"
      height="317px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "Calendar3")}
      {...rest}
    >
      <View
        width="251px"
        height="238px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="24.92%"
        left="0%"
        right="0%"
        boxShadow="0px 1px 4px rgba(0, 0, 0, 0.25)"
        borderRadius="4px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(255,255,255,1)"
        {...getOverrideProps(overrides, "Rectangle 147")}
      ></View>
      <Icon
        width="23px"
        height="20px"
        viewBox={{ minX: 0, minY: 0, width: 23, height: 20 }}
        paths={[
          {
            d: "M0 2C0 0.895431 0.895431 0 2 0L21 0C22.1046 0 23 0.895431 23 2L23 18C23 19.1046 22.1046 20 21 20L2 20C0.89543 20 0 19.1046 0 18L0 2Z",
            fill: "rgba(4,125,149,1)",
            fillRule: "nonzero",
          },
        ]}
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="35.65%"
        bottom="58.04%"
        left="33.47%"
        right="57.37%"
        {...getOverrideProps(overrides, "Rectangle 150")}
      ></Icon>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="20px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="17.03%"
        bottom="78.55%"
        left="9.56%"
        right="82.47%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Mo"
        {...getOverrideProps(overrides, "Mo")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="13px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="17.03%"
        bottom="78.55%"
        left="61.35%"
        right="33.47%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Fr"
        {...getOverrideProps(overrides, "Fr")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="21px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="17.03%"
        bottom="78.55%"
        left="34.26%"
        right="57.37%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="We"
        {...getOverrideProps(overrides, "We")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="16px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="17.03%"
        bottom="78.55%"
        left="86.45%"
        right="7.17%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Su"
        {...getOverrideProps(overrides, "Su")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="14px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="46.69%"
        bottom="48.9%"
        left="61.35%"
        right="33.07%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="16"
        {...getOverrideProps(overrides, "16")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="13px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="36.28%"
        bottom="59.31%"
        left="61.35%"
        right="33.47%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="11"
        {...getOverrideProps(overrides, "11")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="17px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="56.78%"
        bottom="38.8%"
        left="61.35%"
        right="31.87%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="23"
        {...getOverrideProps(overrides, "23")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="17px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="65.93%"
        bottom="29.65%"
        left="61.35%"
        right="31.87%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="30"
        {...getOverrideProps(overrides, "3037823993")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="15px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="56.78%"
        bottom="38.8%"
        left="22.31%"
        right="71.71%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="20"
        {...getOverrideProps(overrides, "20")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="15px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="46.69%"
        bottom="48.9%"
        left="22.31%"
        right="71.71%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="13"
        {...getOverrideProps(overrides, "1337823995")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="13px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="36.28%"
        bottom="59.31%"
        left="22.31%"
        right="72.51%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children=" 8"
        {...getOverrideProps(overrides, "8")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="0px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="26.18%"
        bottom="69.4%"
        left="22.31%"
        right="77.69%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="  "
        {...getOverrideProps(overrides, "Text")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="15px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="65.93%"
        bottom="29.65%"
        left="22.31%"
        right="71.71%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="27"
        {...getOverrideProps(overrides, "27")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="15px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="56.78%"
        bottom="38.8%"
        left="9.56%"
        right="84.46%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="19"
        {...getOverrideProps(overrides, "19")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="15px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="46.69%"
        bottom="48.9%"
        left="9.56%"
        right="84.46%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="12"
        {...getOverrideProps(overrides, "1237824000")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="12px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="36.28%"
        bottom="59.31%"
        left="9.56%"
        right="85.66%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children=" 7"
        {...getOverrideProps(overrides, "7")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(177,177,178,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="16px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="26.18%"
        bottom="69.4%"
        left="9.56%"
        right="84.06%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="30"
        {...getOverrideProps(overrides, "3037824002")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="16px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="65.93%"
        bottom="29.65%"
        left="9.56%"
        right="84.06%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="26"
        {...getOverrideProps(overrides, "26")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="15px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="46.69%"
        bottom="48.9%"
        left="74.1%"
        right="19.92%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="17"
        {...getOverrideProps(overrides, "17")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="15px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="36.28%"
        bottom="59.31%"
        left="74.1%"
        right="19.92%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="12"
        {...getOverrideProps(overrides, "1237824005")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="14px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="26.18%"
        bottom="69.4%"
        left="74.1%"
        right="20.32%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children=" 5"
        {...getOverrideProps(overrides, "5")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="17px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="56.78%"
        bottom="38.8%"
        left="74.1%"
        right="19.12%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="24"
        {...getOverrideProps(overrides, "24")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="15px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="65.93%"
        bottom="29.65%"
        left="74.1%"
        right="19.92%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="31"
        {...getOverrideProps(overrides, "31")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="14px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="56.78%"
        bottom="38.8%"
        left="35.46%"
        right="58.96%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="21"
        {...getOverrideProps(overrides, "21")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="14px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="46.69%"
        bottom="48.9%"
        left="35.46%"
        right="58.96%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="14"
        {...getOverrideProps(overrides, "14")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(255,255,255,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="13px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="36.28%"
        bottom="59.31%"
        left="35.46%"
        right="59.36%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children=" 9"
        {...getOverrideProps(overrides, "9")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(124,124,124,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="16px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="26.18%"
        bottom="69.4%"
        left="35.46%"
        right="58.17%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="  2"
        {...getOverrideProps(overrides, "2")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(124,124,124,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="15px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="26.18%"
        bottom="69.4%"
        left="22.31%"
        right="71.71%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="  1"
        {...getOverrideProps(overrides, "137824013")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(124,124,124,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="17px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="26.18%"
        bottom="69.4%"
        left="59.76%"
        right="33.47%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="  4"
        {...getOverrideProps(overrides, "4")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="16px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="65.93%"
        bottom="29.65%"
        left="35.46%"
        right="58.17%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="28"
        {...getOverrideProps(overrides, "28")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="15px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="46.69%"
        bottom="48.9%"
        left="86.85%"
        right="7.17%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="18"
        {...getOverrideProps(overrides, "18")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="15px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="36.28%"
        bottom="59.31%"
        left="86.85%"
        right="7.17%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="13"
        {...getOverrideProps(overrides, "1337824017")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="13px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="26.18%"
        bottom="69.4%"
        left="87.65%"
        right="7.17%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children=" 6"
        {...getOverrideProps(overrides, "6")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="16px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="56.78%"
        bottom="38.8%"
        left="86.45%"
        right="7.17%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="25"
        {...getOverrideProps(overrides, "25")}
      ></Text>
      <Text
        fontFamily="Inter"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="13.3125px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="12px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="65.93%"
        bottom="29.65%"
        left="88.05%"
        right="7.17%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children=" 1"
        {...getOverrideProps(overrides, "137824020")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="15px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="56.78%"
        bottom="38.8%"
        left="49%"
        right="45.02%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="22"
        {...getOverrideProps(overrides, "22")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="14px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="46.69%"
        bottom="48.9%"
        left="49%"
        right="45.42%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="15"
        {...getOverrideProps(overrides, "15")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="14px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="36.28%"
        bottom="59.31%"
        left="49%"
        right="45.42%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="10"
        {...getOverrideProps(overrides, "10")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(124,124,124,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="11px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="26.18%"
        bottom="69.4%"
        left="49%"
        right="46.61%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children=" 3"
        {...getOverrideProps(overrides, "3")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="15px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="65.93%"
        bottom="29.65%"
        left="49%"
        right="45.02%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="29"
        {...getOverrideProps(overrides, "29")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="15px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="17.03%"
        bottom="78.55%"
        left="22.31%"
        right="71.71%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Tu"
        {...getOverrideProps(overrides, "Tu")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="16px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="17.03%"
        bottom="78.55%"
        left="73.71%"
        right="19.92%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Sa"
        {...getOverrideProps(overrides, "Sa")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="11px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="16.5px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="15px"
        height="14px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="17.03%"
        bottom="78.55%"
        left="49%"
        right="45.02%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="Th"
        {...getOverrideProps(overrides, "Th")}
      ></Text>
      <View
        width="100px"
        height="302px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="4.73%"
        bottom="0%"
        left="58.17%"
        right="1.99%"
        borderRadius="4px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(243,243,243,1)"
        {...getOverrideProps(overrides, "Rectangle 513")}
      ></View>
      <Text
        fontFamily="Poppins"
        fontSize="12px"
        fontWeight="400"
        color="rgba(37,37,37,1)"
        lineHeight="18px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="37.84px"
        height="12.11px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="6.45%"
        bottom="89.73%"
        left="61.39%"
        right="23.53%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="2022"
        {...getOverrideProps(overrides, "202237824030")}
      ></Text>
      <View
        width="96px"
        height="22px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="47.63%"
        bottom="45.43%"
        left="58.17%"
        right="3.59%"
        borderRadius="4px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(4,125,149,1)"
        {...getOverrideProps(overrides, "Rectangle 514")}
      ></View>
      <Icon
        width="10.6px"
        height="7.57px"
        viewBox={{
          minX: 0,
          minY: 0,
          width: 10.596435546875,
          height: 7.56884765625,
        }}
        paths={[
          {
            d: "M5.29819 0L9.88656 5.67663L0.709823 5.67663L5.29819 0Z",
            fill: "rgba(4,125,149,1)",
            fillRule: "nonzero",
          },
        ]}
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="10.35%"
        bottom="87.26%"
        left="79.28%"
        right="16.5%"
        transformOrigin="top left"
        transform="rotate(-180deg)"
        {...getOverrideProps(overrides, "Polygon 19")}
      ></Icon>
      <Icon
        width="10.6px"
        height="7.57px"
        viewBox={{
          minX: 0,
          minY: 0,
          width: 10.596435546875,
          height: 7.56884765625,
        }}
        paths={[
          {
            d: "M5.29819 0L9.88656 5.67663L0.709823 5.67663L5.29819 0Z",
            fill: "rgba(4,125,149,1)",
            fillRule: "nonzero",
          },
        ]}
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="7.88%"
        bottom="89.73%"
        left="52.74%"
        right="43.04%"
        transformOrigin="top left"
        transform="rotate(0deg)"
        {...getOverrideProps(overrides, "Polygon 20")}
      ></Icon>
      <Text
        fontFamily="Poppins"
        fontSize="12px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="18px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="72px"
        height="17px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="6.31%"
        bottom="88.33%"
        left="24.7%"
        right="46.61%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="December "
        {...getOverrideProps(overrides, "December")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="12px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="18px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="72px"
        height="17px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="13.25%"
        bottom="81.39%"
        left="62.55%"
        right="8.76%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="2023"
        {...getOverrideProps(overrides, "2023")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="12px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="18px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="72px"
        height="19px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="19.87%"
        bottom="74.13%"
        left="62.55%"
        right="8.76%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="2022 "
        {...getOverrideProps(overrides, "202237824036")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="12px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="18px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="72px"
        height="18px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="27.13%"
        bottom="67.19%"
        left="62.55%"
        right="8.76%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="2021"
        {...getOverrideProps(overrides, "202137824037")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="12px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="18px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="72px"
        height="18px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="34.07%"
        bottom="60.25%"
        left="62.55%"
        right="8.76%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="2020"
        {...getOverrideProps(overrides, "2020")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="12px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="18px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="72px"
        height="17px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="41.32%"
        bottom="53.31%"
        left="62.55%"
        right="8.76%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="2019"
        {...getOverrideProps(overrides, "2019")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="12px"
        fontWeight="400"
        color="rgba(255,255,255,1)"
        lineHeight="18px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="72px"
        height="18px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="47.95%"
        bottom="46.37%"
        left="62.55%"
        right="8.76%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="2018"
        {...getOverrideProps(overrides, "2018")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="12px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="18px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="72px"
        height="17px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="55.21%"
        bottom="39.43%"
        left="62.55%"
        right="8.76%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="2021"
        {...getOverrideProps(overrides, "202137824041")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="12px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="18px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="72px"
        height="17px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="62.15%"
        bottom="32.49%"
        left="62.55%"
        right="8.76%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="2021"
        {...getOverrideProps(overrides, "202137824042")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="12px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="18px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="72px"
        height="19px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="68.77%"
        bottom="25.24%"
        left="62.55%"
        right="8.76%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="2021"
        {...getOverrideProps(overrides, "202137824043")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="12px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="18px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="72px"
        height="18px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="76.03%"
        bottom="18.3%"
        left="62.55%"
        right="8.76%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="2021"
        {...getOverrideProps(overrides, "202137824044")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="12px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="18px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="72px"
        height="18px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="82.97%"
        bottom="11.36%"
        left="62.55%"
        right="8.76%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="2021"
        {...getOverrideProps(overrides, "202137824045")}
      ></Text>
      <Text
        fontFamily="Poppins"
        fontSize="12px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="18px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="72px"
        height="17px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="90.22%"
        bottom="4.42%"
        left="62.55%"
        right="8.76%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="2021"
        {...getOverrideProps(overrides, "202137824046")}
      ></Text>
      <View
        width="4px"
        height="302px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="4.73%"
        bottom="0%"
        left="96.41%"
        right="1.99%"
        borderRadius="0px 4px 4px 0px"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(167,167,167,1)"
        {...getOverrideProps(overrides, "Rectangle 516")}
      ></View>
      <View
        width="4px"
        height="36px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="29.34%"
        bottom="59.31%"
        left="96.41%"
        right="1.99%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(237,32,36,1)"
        {...getOverrideProps(overrides, "Rectangle 515")}
      ></View>
    </View>
  );
}
